spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-flyway?autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Tokyo

server:
  port: 8081
  servlet:
    context-path: /api
env:
  session:
    maximumSessions: 1
    timeout: 14400
logging:
  level:
    root: INFO
